version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      # - front
      - wordpress
      - db
    # links:
    # - front
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
  front:
    networks:
      - app_network
    container_name: front
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - db
      - wordpress
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    command: node .output/server/index.mjs
  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./back/wp-content:/var/www/html/wp-content
    networks:
      - app_network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app_network
    command: "--default-authentication-plugin=mysql_native_password"
volumes:
  wordpress:
  db:
networks:
  app_network:
    driver: bridge
