version: "3"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./front
    container_name: baligo-docker-frontend
    restart: unless-stopped
    command: node .output/server/index.mjs
    networks:
      - baligo-docker-network
  wordpress:
    image: wordpress
    container_name: baligo-docker-wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html/back
    networks:
      - baligo-docker-network
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: baligo-docker-db
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
    networks:
      - baligo-docker-network
  nginx:
    image: nginx:stable-alpine
    container_name: baligo-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/usr/share/nginx/html
    depends_on:
      - frontend
      - db
      - wordpress
    networks:
      - baligo-docker-network

volumes:
  wordpress:
  db:
networks:
  baligo-docker-network:
    driver: bridge
